#!/bin/bash

DO_PREREQ=0
DO_INSTALLHL=0
DO_STARTHL=0
DO_STOPHL=0
export FABRIC_VERSION=hlfv12
cd $(dirname "$0")

install_package () {
	package=$1
	if [ $(dpkg-query -W -f='${Status}' $package 2>/dev/null | grep -c "ok installed") -eq 0 ]
	then
	  sudo apt-get install -y $package -qq > /dev/null
	fi
}

prereq () {
	echo "Step 1: Install Pre-requisites"
	install_package curl
	install_package jq
	curl -O https://hyperledger.github.io/composer/latest/prereqs-ubuntu.sh
	source /etc/lsb-release
	sed -i -e "s/yakkety/${DISTRIB_CODENAME}/g" prereqs-ubuntu.sh
	chmod u+x prereqs-ubuntu.sh
	./prereqs-ubuntu.sh
}

installHyperledgerServers () {
	npm install -g composer-cli@latest
	npm install -g composer-rest-server@latest
	npm install -g composer-playground@latest
	mkdir ./fabric-dev-servers
	curl -O https://raw.githubusercontent.com/hyperledger/composer-tools/master/packages/fabric-dev-servers/fabric-dev-servers.tar.gz
	tar -xvf fabric-dev-servers.tar.gz -C ./fabric-dev-servers/
	rm fabric-dev-servers.tar.gz
	./fabric-dev-servers/downloadFabric.sh
}

startHyperledgerServers () {
	./fabric-dev-servers/startFabric.sh
	if [ ! -f ./DevServer_connection.json ]; then
		./fabric-dev-servers/createPeerAdminCard.sh	
	fi
	docker rm $(docker ps -qa --no-trunc --filter "status=exited" --filter name=dev-peer0.org1.example.com-watcher-network)
	docker volume prune -f
	docker network prune -f
	composer network install --card PeerAdmin@hlfv1 --archiveFile watcher-network.bna
	NET_VERSION=$(unzip -c watcher-network.bna package.json | tail -n -1 | jq -r '.version')
	composer card delete -c admin@watcher-network
	composer card delete -c watcher@watcher-network
	composer card delete -c umbrella@watcher-network
	composer card delete -c cyberdyne@watcher-network
	composer network start --networkName watcher-network --networkVersion $NET_VERSION --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file admin@watcher-network.card
	composer card import -f admin@watcher-network.card
	composer participant add --card admin@watcher-network --data '{"$class": "watcher.model.Organization","id": "org1","name": "Watcher"}'	
	composer participant add --card admin@watcher-network --data '{"$class": "watcher.model.Organization","id": "org2","name": "Umbrella"}'
	composer participant add --card admin@watcher-network --data '{"$class": "watcher.model.Organization","id": "org3","name": "Cyberdyne"}'
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.Application",
   "id": "os",
   "name": "Operative System"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.Application"}'	
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.Application",
   "id": "ro",
   "name": "Root Session"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.Application"}'	
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.Application",
   "id": "snmp",
   "name": "Simple Network Management Protocol"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.Application"}'	
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.EventType",
  "id": "oscr",
  "name": "Operative System - Create File",
  "application": "resource:watcher.model.Application#os"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.EventType"}'	
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.EventType",
  "id": "osac",
  "name": "Operative System - Access File",
  "application": "resource:watcher.model.Application#os"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.EventType"}'	
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.EventType",
  "id": "rose",
  "name": "Root Session",
  "application": "resource:watcher.model.Application#ro"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.EventType"}'	
	composer transaction submit --card admin@watcher-network --data '{
 "$class": "org.hyperledger.composer.system.AddAsset",
 "resources": [
  {
   "$class": "watcher.model.EventType",
  "id": "snla",
  "name": "SNMP - Incorrect Login",
  "application": "resource:watcher.model.Application#os"
  }
 ],
 "targetRegistry": "resource:org.hyperledger.composer.system.AssetRegistry#watcher.model.EventType"}'	
	composer identity issue -c admin@watcher-network -f watch.card -u watcher -a resource:watcher.model.Organization#org1
	composer identity issue -c admin@watcher-network -f umbrella.card -u umbrella -a resource:watcher.model.Organization#org2
	composer identity issue -c admin@watcher-network -f cyberdyne.card -u cyberdyne -a resource:watcher.model.Organization#org3
	composer card import -f watch.card
	composer card import -f umbrella.card
	composer card import -f cyberdyne.card
	nohup composer-playground > ./composer-playground-node-server.out &
	nohup composer-rest-server -c watcher@watcher-network -n always -w true > ./composer-rest-server.out &
	nohup composer-rest-server -c umbrella@watcher-network -n always -w true -p 3001 > ./composer-rest-server.out &
	nohup composer-rest-server -c cyberdyne@watcher-network -n always -w true -p 3002 > ./composer-rest-server.out &
	echo "wait another 15 seconds..."
	sleep 15
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accesspasswd","name": "Access to /etc/passwd","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/passwd\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accesspasswd\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accessshadow","name": "Access to /etc/shadow","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/shadow\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accessshadow\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accessgroups","name": "Access to /etc/groups","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/groups\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accessgroups\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accessgshadow","name": "Access to /etc/gshadow","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/gshadow\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accessgshadow\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accesslogin","name": "Access to /etc/login.defs","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/login.defs\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accesslogin\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accessshells","name": "Access to /etc/shells","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/shells\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accessshells\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "accesssecuretty","name": "Access to /etc/securetty","typesInvolved": ["resource:watcher.model.EventType#osac"],"URLs": ["event-os-{TODAY}-osac,event-os-{TODAY-1}-osac/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"file_created.keyword\":\"/etc/securetty\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"accesssecuretty\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom1","name": "Ransomware ecc","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*ecc\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom1\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom2","name": "Ransomware ezz","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*ezz\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom2\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom3","name": "Ransomware exx","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*exx\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom3\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom4","name": "Ransomware zzz","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*zzz\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom4\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom5","name": "Ransomware xyz","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*xyz\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom5\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom6","name": "Ransomware aaa","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*aaa\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom6\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom7","name": "Ransomware abc","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*abc\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom7\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom8","name": "Ransomware ccc","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*ccc\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom8\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom9","name": "Ransomware vvv","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*vvv\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom9\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "ransom10","name": "Ransomware xxx","typesInvolved": ["resource:watcher.model.EventType#oscr"],"URLs": ["event-os-{TODAY}-oscr,event-os-{TODAY-1}-oscr/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"regexp\":{\"file_created\":\".*xxx\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"ransom10\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.file_created","_source.event_date"]}' 
	#ADD RULE TO ACCESS ROOT 3 times in same minute -> AGGREGATOR https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html
	#CAN BE DONE WITH TOP_HITS. ADD AN OPTIONAL FIELD IN BLOCKCHAIN TO CHANGE THE LOOP NODE.
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "rootnonworkinghours","name":"Access to root on non-working hours", "typesInvolved": ["resource:watcher.model.EventType#rose"],"URLs": ["event-ro-{TODAY}-rose/events","event-ro-{TODAY}-rose/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\": {\"range\": { \"_source.event_date\": {\"gt\" : \"{TODAY}T18:00:00.00\"}}},\"must_not\":{\"term\" :{\"internal_ruleId\":\"rootnonworkinghours\"}}}}}","{\"query\":{\"bool\":{\"must\": {\"range\": { \"_source.event_date\":{ \"lt\" : \"{TODAY}T8:00:00.00\"}}},\"must_not\":{\"term\" :{\"internal_ruleId\":\"rootnonworkinghours\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.event_date"]}' &
	curl 'http://localhost:3000/api/watcher.transaction.AddRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id": "snmpincorrectadmin","name":"Incorrect login from admin user", "typesInvolved": ["resource:watcher.model.EventType#snla"],"URLs": ["event-sn-{TODAY}-snla/events"],"DSLs": ["{\"query\":{\"bool\":{\"must\":[{\"term\":{\"user_name.keyword\":\"admin\"}}],\"must_not\":{\"term\" :{\"internal_ruleId\":\"snmpincorrectadmin\"}}}}}"],"fieldsOutputPath": ["_source.source_host","_source.monitorization_date","_source.event_date","_source.ip_user"]}'
	echo "wait another 20 to add endoresements..."
	sleep 20
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#accesspasswd"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#accessshadow"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#accessgroups"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#accesslogin"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#accessshells"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#accesssecuretty"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom1"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom2"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom3"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom4"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom5"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom6"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom7"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom8"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom9"}' &
	curl 'http://localhost:3001/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom10"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom1"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom2"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom3"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom4"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom5"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom6"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom7"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom8"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom9"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#ransom10"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#rootnonworkinghours"}' &
	curl 'http://localhost:3002/api/watcher.transaction.EndorseRule' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "rule": "resource:watcher.model.Rule#snmpincorrectadmin"}' 
	
	sleep 5
	#ADD RULE TO INCORRECT LOGINS IN 5 MINUTES FOR SNMP
	#ADD RULE TO SNMP LOGIN FROM INCORRECT IPS
}

stopHyperledgerServers () {
	kill $(ps aux | grep composer-playground | grep bin | awk '{print $2}')
	kill $(ps aux | grep composer-rest-server | grep bin | awk '{print $2}')
	./fabric-dev-servers/stopFabric.sh
}

if [[ $# -eq 0 ]] ; then
    echo 'No parameters, No Party.'
    echo 'All party: steps -prereq -install -start -stop' 
    exit 0
fi

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    case $PARAM in
        -prereq)
            DO_PREREQ=1
            ;;
        -install)
            DO_INSTALLHL=1
            ;;
        -start)
            DO_STARTHL=1
            ;;
        -stop)
            DO_STOPHL=1
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            exit 1
            ;;
    esac
    shift
done

if [[ $DO_PREREQ -eq 1 ]]; then
   prereq
fi

if [[ $DO_INSTALLHL -eq 1 ]]; then
   installHyperledgerServers
fi

if [[ $DO_STARTHL -eq 1 ]]; then
   startHyperledgerServers
fi

if [[ $DO_STOPHL -eq 1 ]]; then
   stopHyperledgerServers
fi

echo "ALL STEPS DONE"
