
version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8086:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./html:/var/www/html
  mysql:
    image: mariadb:latest
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_USER: wordpress
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
    - ./wpdb:/var/lib/mysql
